port: 3000

postgresql:
  auth:
    database: "wlosiara-pl-quizzes-service"
    username: "wlosiara-pl-quizzes-service"
    password: null # required
  primary:
    initdb:
      scripts-configmap: "wlosiara-pl-quizzes-service-initdb-scripts"
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
    persistence:
      size: "1Gi"

image:
  dockerRegistry:
    host: null # required

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
